# GitLab Pages deployment configuration
pages:
  stage: deploy
  script:
    # The app is static, so we just need to copy files to public/
    - mkdir -p public
    - cp -r index.html app.js mode-help.js themes/ public/
    # Create a simple 404 page that redirects to index.html
    - echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/index.html"></head></html>' > public/404.html
  artifacts:
    paths:
      - public
  only:
    - main
    - master