# GitLab CI/CD Configuration for Regex Tester
# Simple deployment to GitLab Pages

pages:
  stage: deploy
  script:
    # Create public directory
    - mkdir -p public
    
    # Copy the single HTML file
    - cp index.html public/
    
  artifacts:
    paths:
      - public
    expire_in: 1 week
    
  only:
    # Deploy only from main/master branch
    - main
    - master